### ISSUE TITLE
JIT Error: Unable to create user because missing claims (emailaddress)

### ISSUE THREAD

**Issue by Antcares** [derricksmith/phpsaml#108]
Hello! I have configured the plugin in GLPI 9.5.9 and is functioning properly, but i am having this error when JIT is enabled and the user don't exist in GLPI:

JIT Error: Unable to create user because missing claims (emailaddress)

My IdP is keycloak, and i have created a mapper named emailaddress for send the email in te response (i attach the SAML file). Any help is appreciated.
![SAML_response](https://user-images.githubusercontent.com/54274061/194105164-ae5dc542-7dd3-49f7-a7fb-db6dae463741.png)

**Comment by derricksmith** [comment]
I took a look at phpsaml.class.php on line 84 and noticed that JIT requires both name and emailaddress to create the user.

http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress

I updated the error message to check which claim is missing.

$missing = (empty(SELF::$userdata['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name'][0]) ? 'name' : 'emailaddress');
$error = "JIT Error: Unable to create user because missing claims ($missing)";

**Comment by SilvaFernando** [comment]
Good night everybody!!!!

This

> Hello, working with GLPI 10.0.5 and this wonderfull plugin :) I'm having the same error using SAML2 federation.
> 
> I comment this in phpsaml.class.php (line 84)
> 
> `// if ((!empty(self::$userdata['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name'][0])) && (!empty(self::$userdata['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress'][0]))){`
> 
> replace by :
> 
> `if ((!empty(self::$userdata['name'][0])) && (!empty(self::$userdata['emailaddress'][0]))){`
> 
> as $userdata is an array.
> 
> And also line 90-93 comment this :
> 
> ```
> // "name" => self::$userdata['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name'][0],
> // "realname" => self::$userdata['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname'][0],
> // "firstname" => self::$userdata['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/firstname'][0],
> // "_useremails" => array(self::$userdata['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress'][0]),
> ```
> 
> by
> 
> ```
> "name" => self::$userdata['name'][0],
> "realname" => self::$userdata['lastname'][0],
> "firstname" => self::$userdata['firstname'][0],
> "_useremails" => array(self::$userdata['emailaddress'][0]),
> ```
> 
> I'va been able to JIT provisionning a new user and map some attributes (email, firstname realname and Login Name)
> 
> Best regards
> 
> Laurent
THanks, i do this in code and Gsuite authentication worked, i have one question, if we need mapping other attributes, it's possible?

**Comment by Loz-001** [comment]
Sorry, I've not been able to map other attributes yet.

I would like to have at least the phone number to be mapped. If someone knows how-to add it :)

Laurent

**Comment by SilvaFernando** [comment]
@derricksmith, can you help us with this?

Thanks :)

**Comment by DonutsNL** [comment]
Todo: Add additional JIT validations to phpsaml.class.php : private static function performJit($relayState)

**Comment by DonutsNL** [comment]
Should be solved in my latest branch.

**Comment by jbtele29** [comment]
Hello,
I always have this problem with a specific user.
I tried 1.3.0 version @DonutsNL fork but i still have a problem with this user
`2023-07-10 17:58:34 [@govihan2023]
JIT Error: Unable to create user because missing claims (emailaddress)
2023-07-10 17:58:34 [@govihan2023]
JIT Error: Unable to create user because missing claims (emailaddress)
[2023-07-10 17:58:34] glpiphplog.WARNING:   *** PHP Warning (2): Undefined global variable $_POST in /var/www/html/glpi/src/Application/View/TemplateRenderer.php at line 120
  Backtrace :
  src/Application/View/TemplateRenderer.php:135      Glpi\Application\View\TemplateRenderer->__construct()
  src/Html.php:1296                                  Glpi\Application\View\TemplateRenderer::getInstance()
  src/Html.php:2026                                  Html::includeHeader()
  plugins/phpsaml/front/acs.php:62                   Html::nullHeader()
  public/index.php:82                                require()
`
thanks

**Comment by DonutsNL** [comment]
Hi,

It looks like no saml response is received by the acs. Make sure the asserter url is correct and an saml response body is posted to the front/acs.php

**Comment by jbtele29** [comment]
Hello,

I think that the configuration on the adfs is not good but other users don't have sso problems when they test.
I have this claims on adfs
![image](https://github.com/derricksmith/phpsaml/assets/139154287/21b6e05d-efe0-41a0-bcd6-c58f742c0adf)

**Comment by DonutsNL** [comment]
If you use the latest version of my branch you can actually dump the samlresponse and review it to see what is going wrong. To dump the responses:

1. create a folder 'debug' inside the plugin directory;
2. enable debug in the phpsaml config page;
3. Replay the login, this should create a .php file in the debug folder.
4. Open the dumped .php file to review the SamlResponse provided;
5. It should have the missing claim:
6.       http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress

**Comment by jbtele29** [comment]
Hello , 
Yes i have samlreponse in debug folder and i used your for branch 
![image](https://github.com/derricksmith/phpsaml/assets/139154287/2d7e90cb-c6d8-4831-aa13-b934f80eb557)
but when i clikc for login, nothing change and i come back to login again
in dump i had same info from your deleted dump in your branch

**Comment by jbtele29** [comment]
Hi,
I found the problem
i imported test accounts on glpi with a different login but the same email as my main account so that was the problem
I deleted the emails on my test accounts in ad and deleted the test accounts in glpi and now everything works as before.
thanks

**Comment by DonutsNL** [comment]
hi @jbtele29,

I am glad you found and fixed the problem. And your feedback is also very usefull. It is true that currently the user creation proces itself is not properly evaluated. Problems during creation are not handled properly. This needs to be handled as well. Ill create a new issue for this problem.
